[package]
name = "reacher_backend"
version = "0.2.3"
edition = "2018"
license = "AGPL-3.0"
publish = false

[dependencies]
async-recursion = "0.3"
async-smtp = { version = "0.3", features = ["socks5"] }
check-if-email-exists = "0.8"
env_logger = "0.7"
http-types = "1.3"
lambda_http = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", branch = "master"}
log = "0.4"
sentry = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
surf = "2.0.0-alpha.2"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"

[dev-dependencies]
serde_json = "1.0"
