[package]
name = "reacher"
version = "0.1.9"
edition = "2018"
publish = false

[dependencies]
check-if-email-exists = { git = "https://github.com/amaurymartiny/check-if-email-exists" }
env_logger = "0.7"
log = "0.4"
sentry = "0.17"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
