[package]
name = "reacher_backend"
version = "0.3.7"
edition = "2018"
license = "AGPL-3.0 OR Commercial"
publish = false

[dependencies]
async-recursion = "0.3"
async-smtp = "0.3"
check-if-email-exists = "0.8"
env_logger = "0.8"
log = "0.4"
sentry = "0.22"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.1", features = ["macros"] }
warp = "0.2"

[dev-dependencies]
serde_json = "1.0"
