name: production

on:
  push:
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

jobs:
  # Build the binary, and publish it as a Github Release
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build static binary
        uses: stevenleadbeater/rust-musl-builder@master
        with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl" # For the Dockerfile

      - name: Set REACHER_VERSION env variable # Will be v*.*.* (major.minor.patch)
        run: echo ::set-env name=REACHER_VERSION::${GITHUB_REF:10} # Remove refs/tags/

      - name: Create .tar.gz
        run: |
          cd ./target/x86_64-unknown-linux-musl/release
          tar -czvf reacher-${{ env.REACHER_VERSION }}-x86_64-unknown-linux-musl.tar.gz reacher
          ls
      # - name: Create a Github Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ./target/x86_64-unknown-linux-musl/release/reacher-${{ env.REACHER_VERSION }}-x86_64-unknown-linux-musl.tar.gz
      #     name: Reacher ${{ env.REACHER_VERSION }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Deploy to Fly (Production)
      #   uses: superfly/flyctl-actions@master
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #   with:
      #     args: "deploy --config fly.production.toml --dockerfile Dockerfile.production --remote-only"
